export default {
zh:{
  app_name:"进销存系统",
  home:"首页",
  products:"商品管理",
  suppliers:"供应商管理",
  customers:"客户管理",
  purchase:"采购管理",
  sales:"销售管理",
  reports:"报表统计",
  salesAmount:"销售金额",
  purchaseAmount:'采购金额',
  
  todaySales:"今日销售额",
  monthSales:"本月销售额",
  productCount:"商品总数",
  lowStockAlert:"库存预警",
  recentOrders:"最近订单",
  salesTrend:"销售趋势",
  
  // 库存预警与毛利
  lowStockList:"库存预警列表",
  adjustStock:"库存调整",
  stockOps:"库存流水",
  newStock:"调整后库存",
  adjustReason:"调整原因",
  profit:"毛利",
  saleAmount:"销售额",
  costAmount:"成本额",
  purchaseAmount:"采购额",
  profitRate:"毛利率",
  changeType:"类型",
  beforeStock:"变动前",
  afterStock:"变动后",
  opType:{PUR:"采购入库",SAL:"销售出库",RET:"退货回补",ADJ:"盘点调整"},
  
  productName:"商品名称",
  category:"分类",
  price:"售价",
  costPrice:"成本价",
  stock:"库存",
  minStock:"最低库存",
  unit:"单位",
  supplier:"供应商",
  remark:"备注",
  addProduct:"添加商品",
  editProduct:"编辑商品",
  deleteProduct:"删除商品",
  search:"搜索",
  reset:"重置",
  save:"保存",
  cancel:"取消",
  confirm:"确认",
  close:"关闭",
  operation:"操作",
  success:"成功",
  failed:"失败",
  
  supplierName:"供应商名称",
  contact:"联系人",
  phone:"电话",
  address:"地址",
  addSupplier:"添加供应商",
  editSupplier:"编辑供应商",
  
  customerName:"客户名称",
  addCustomer:"添加客户",
  editCustomer:"编辑客户",
  
  purchaseOrder:"采购订单",
  orderNo:"订单号",
  totalAmount:"总金额",
  status:"状态",
  creator:"创建人",
  createTime:"创建时间",
  pending:"待入库",
  completed:"已完成",
  createOrder:"创建订单",
  completeOrder:"完成入库",
  completeOutbound:"完成出库",
  orderDetail:"订单详情",
  items:"商品明细",
  summary:"汇总信息",
  quantity:"数量",
  unitPrice:"单价",
  subTotal:"小计",
  
  salesOrder:"销售订单",
  discount:"折扣",
  finalAmount:"实付金额",
  paymentMethod:"支付方式",
  createSalesOrder:"创建销售订单",

  stats:"统计数据",
  topProducts:"热销商品排行",
  amount:"金额",
  noData:"暂无数据",

  // 分类管理
  categories:"分类管理",
  categoryName:"分类名称",
  addCategory:"添加分类",
  editCategory:"编辑分类",
  deleteCategory:"删除分类",

  // 错误提示和表单验证
  pleaseInputProductName:"请输入商品名称",
  pleaseSelectCategory:"请选择分类",
  pleaseInputPrice:"请输入售价",
  pleaseInputCostPrice:"请输入成本价",
  pleaseInputStock:"请输入库存数量",
  pleaseInputSupplierName:"请输入供应商名称",
  pleaseInputCustomerName:"请输入客户名称",
  pleaseAddProduct:"请添加商品",
  pleaseInputQuantity:"请输入数量",
  pleaseInputUnitPrice:"请输入单价",
  pleaseInputContact:"请输入联系人",
  pleaseInputPhone:"请输入电话",
  pleaseInputAddress:"请输入地址",
  pleaseInputRemark:"请输入备注",
  pleaseInputCategoryName:"请输入分类名称",
  pleaseSelectProduct:"请选择商品",
  pleaseSelectCustomer:"请选择客户",
  pleaseInputBarcode:"请输入条形码",
  productNotFound:"未找到该商品",
  insufficientStock:"库存不足",
  scanBarcode:"扫描条形码",
  scanFailed:"扫码失败",
  paymentQRCode:"收款二维码",
  wechatPay:"微信支付",
  alipay:"支付宝",
  scanToPay:"请扫描二维码完成支付",

  // 操作成功/失败提示
  saveSuccess:"保存成功",
  saveFailed:"保存失败",
  deleteSuccess:"删除成功",
  deleteFailed:"删除失败",
  confirmDelete:"确认删除",
  confirmDeleteMessage:"确定要删除这条记录吗？",

  // 支付方式映射
  paymentMethods:{CAS:"现金",WX:"微信",ALP:"支付宝",OTH:"其他"},

  // 其他常用
  loading:"加载中...",
  loadFailed:"加载失败",
  networkError:"网络错误",
  unknownError:"未知错误",
  selectDate:"选择日期",
  startDate:"开始日期",
  endDate:"结束日期",
  export:"导出",
  import:"导入",
  print:"打印",
  refresh:"刷新",
  more:"更多",
  view:"查看",
  edit:"编辑",
  delete:"删除",
  batchDelete:"批量删除",
  total:"共",
  records:"条记录",
  page:"页",
  prevPage:"上一页",
  nextPage:"下一页",
  jumpTo:"跳转到",
  go:"前往",
  orderStatus:[{value:0,label:"未完成"},{value:1,label:"已完成"},{value:-1,label:"全部"}]
},
en:{
  app_name:"Inventory System",
  home:"Home",
  products:"Products",
  suppliers:"Suppliers",
  customers:"Customers",
  purchase:"Purchase",
  sales:"Sales",
  reports:"Reports",
  salesAmount:"Sales Amount",
  purchaseAmount:'Purchase Amount',
  
  todaySales:"Today Sales",
  monthSales:"Month Sales",
  productCount:"Product Count",
  lowStockAlert:"Low Stock Alert",
  recentOrders:"Recent Orders",
  salesTrend:"Sales Trend",
  
  // Low stock & profit
  lowStockList:"Low Stock List",
  adjustStock:"Adjust Stock",
  stockOps:"Stock History",
  newStock:"New Stock",
  adjustReason:"Reason",
  profit:"Profit",
  saleAmount:"Sales Amount",
  costAmount:"Cost Amount",
  purchaseAmount:"Purchase Amount",
  profitRate:"Profit Rate",
  changeType:"Type",
  beforeStock:"Before",
  afterStock:"After",
  opType:{PUR:"Purchase In",SAL:"Sales Out",RET:"Return",ADJ:"Adjust"},
  
  productName:"Product Name",
  category:"Category",
  price:"Price",
  costPrice:"Cost Price",
  stock:"Stock",
  minStock:"Min Stock",
  unit:"Unit",
  supplier:"Supplier",
  remark:"Remark",
  addProduct:"Add Product",
  editProduct:"Edit Product",
  deleteProduct:"Delete Product",
  search:"Search",
  reset:"Reset",
  save:"Save",
  cancel:"Cancel",
  confirm:"Confirm",
  close:"Close",
  operation:"Operation",
  success:"Success",
  failed:"Failed",
  
  supplierName:"Supplier Name",
  contact:"Contact",
  phone:"Phone",
  address:"Address",
  addSupplier:"Add Supplier",
  editSupplier:"Edit Supplier",
  
  customerName:"Customer Name",
  addCustomer:"Add Customer",
  editCustomer:"Edit Customer",
  
  purchaseOrder:"Purchase Order",
  orderNo:"Order No",
  totalAmount:"Total Amount",
  status:"Status",
  creator:"Creator",
  createTime:"Create Time",
  pending:"Pending",
  completed:"Completed",
  createOrder:"Create Order",
  completeOrder:"Complete Inbound",
  completeOutbound:"Complete Outbound",
  orderDetail:"Order Detail",
  items:"Items",
  summary:"Summary",
  quantity:"Quantity",
  unitPrice:"Unit Price",
  subTotal:"Subtotal",
  addItem:"Add Item",
  
  salesOrder:"Sales Order",
  discount:"Discount",
  finalAmount:"Final Amount",
  paymentMethod:"Payment Method",
  createSalesOrder:"Create Sales Order",

  stats:"Statistics",
  topProducts:"Top Products",
  amount:"Amount",
  noData:"No Data",

  // Category Management
  categories:"Categories",
  categoryName:"Category Name",
  addCategory:"Add Category",
  editCategory:"Edit Category",
  deleteCategory:"Delete Category",

  // Error Messages and Form Validation
  pleaseInputProductName:"Please enter product name",
  pleaseSelectCategory:"Please select category",
  pleaseInputPrice:"Please enter price",
  pleaseInputCostPrice:"Please enter cost price",
  pleaseInputStock:"Please enter stock quantity",
  pleaseInputSupplierName:"Please enter supplier name",
  pleaseInputCustomerName:"Please enter customer name",
  pleaseAddProduct:"Please add products",
  pleaseInputQuantity:"Please enter quantity",
  pleaseInputUnitPrice:"Please enter unit price",
  pleaseInputContact:"Please enter contact person",
  pleaseInputPhone:"Please enter phone number",
  pleaseInputAddress:"Please enter address",
  pleaseInputRemark:"Please enter remark",
  pleaseInputCategoryName:"Please enter category name",
  pleaseSelectProduct:"Please select product",
  pleaseSelectCustomer:"Please select customer",
  pleaseInputBarcode:"Please enter barcode",
  productNotFound:"Product not found",
  insufficientStock:"Insufficient stock",
  scanBarcode:"Scan Barcode",
  scanFailed:"Scan failed",
  paymentQRCode:"Payment QR Code",
  wechatPay:"WeChat Pay",
  alipay:"Alipay",
  scanToPay:"Please scan the QR code to complete payment",

  // Operation Success/Failure Messages
  saveSuccess:"Saved successfully",
  saveFailed:"Save failed",
  deleteSuccess:"Deleted successfully",
  deleteFailed:"Delete failed",
  confirmDelete:"Confirm Delete",
  confirmDeleteMessage:"Are you sure to delete this record?",

  // Payment Method Mapping
  paymentMethods:{CAS:"Cash",WX:"WeChat",ALP:"AliPay",OTH:"Other"},

  // Other Common Terms
  loading:"Loading...",
  loadFailed:"Load failed",
  networkError:"Network error",
  unknownError:"Unknown error",
  selectDate:"Select Date",
  startDate:"Start Date",
  endDate:"End Date",
  export:"Export",
  import:"Import",
  print:"Print",
  refresh:"Refresh",
  more:"More",
  view:"View",
  edit:"Edit",
  delete:"Delete",
  batchDelete:"Batch Delete",
  total:"Total",
  records:"records",
  page:"Page",
  prevPage:"Previous",
  nextPage:"Next",
  jumpTo:"Jump to",
  go:"Go",
  orderStatus:[{value:0,label:"Waiting"},{value:1,label:"Finished"},{value:-1,label:"All"}]
}
}
